services:
  - type: web
    name: pr-tracker
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn --pythonpath . ave_calculator.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: ave_calculator.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: pr-tracker-db
          property: connectionString
      - key: RENDER
        value: true

databases:
  - name: pr-tracker-db
    databaseName: pr_tracker
    user: pr_tracker_user
