# Generated by Django 4.2.11 on 2025-03-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverage',
            old_name='size_sq_cm',
            new_name='size',
        ),
        migrations.AddField(
            model_name='coverage',
            name='rate_per_sq_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Size (sq cms)'),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='type',
            field=models.CharField(choices=[('Print', 'Print'), ('Online', 'Online'), ('color', 'Color'), ('bw', 'Black & White')], default='Print', max_length=20),
        ),
    ]
